name: check
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Test Framework
        run: |
          sudo apt-get update
          sudo apt-get install -y shunit2

      - name: Run Tests
        run: ./test_ubsetup.sh
